Reapply "Release 0.1-beta.1+2.1.3"
This reverts commit 321027fbd48eaffcf576d44cbf6109b1a9771852.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -53,12 +53,24 @@ jobs:
         id: validate
         shell: pwsh
         run: |
+          # Récupère le nom du tag en supprimant le préfixe "v"
           $tagName = "${{ github.ref_name }}"
+          Import-Module -Name PSSemVer -ErrorAction Stop
           try {
               $rawVersion = $tagName -replace '^v', ''
               $Version = [PSSemVer]::Parse($rawVersion)
-              echo "prerelease=$($Version.Prerelease -ne $null)" >> $env:GITHUB_ENV
-              echo "nuget_version=$($Version.metadata)" >> $env:GITHUB_ENV
+              
+              # Forcer le booléen à une chaîne en minuscules
+              $prereleaseValue = ($Version.Prerelease -ne $null).ToString().ToLower()
+              echo "prerelease=$prereleaseValue" >> $env:GITHUB_ENV
+
+              # Vérifier que le champ metadata est renseigné pour la version NuGet
+              if (-not [string]::IsNullOrEmpty($Version.metadata)) {
+                echo "nuget_version=$($Version.metadata)" >> $env:GITHUB_ENV
+              } else {
+                Write-Error "Metadata is empty. Cannot determine NuGet version."
+                exit 1
+              }
           } catch {
               Write-Error "Tag name does not contain a valid semantic version. Current tag: $tagName"
               exit 1
